---
title: "Aligning Faculty Activities with UN Sustainable Development Goals"
subtitle: "Faculty Input Survey"
date: last-modified
from: markdown+emoji

# format:
#   html:
#     css: custom.css

comments: false
code-fold: false

execute: 
  warning: false
  message: false
  fig-width: 9
  fig-height: 7
  fig-align: center
  eval: false
---
```{r}
#| include: false

library(tidyverse)
library(skimr)
library(DT)
library(hrbrthemes)

theme_set(theme_ipsum() +
          theme(strip.background =element_rect(fill="lightgray"),
                axis.title.x = element_text(size = rel(1.5)),
                axis.title.y = element_text(size = rel(1.5)),
                legend.title = element_text(size=rel(1.25))
                ))
```

The Positive Societal Impact (PSI) Committee invites you to share how your teaching, research, and service activities support the School of Business’s commitment to key United Nations **Sustainable Development Goals (SDGs)**. Your insights are essential in helping us enhance our collective impact. To learn more about each goal, please click the links below:

1. [**Quality Education (Goal 4)**](https://www.globalgoals.org/goals/4-quality-education/): Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all.
2. [**Decent Work and Economic Growth (Goal 8)**](https://www.globalgoals.org/goals/8-decent-work-and-economic-growth/): Promote sustained, inclusive, and sustainable economic growth, full and productive employment, and decent work for all.
3. [**Reduced Inequality (Goal 10)**](https://www.globalgoals.org/goals/10-reduced-inequalities/): Reduce inequality within and among countries.

Please provide descriptions of how your work aligns with these SDGs, including relevant courses, projects, service roles, publications, or other academic contributions. If an SDG does not pertain to your current work, simply leave that section blank or indicate **"Not Applicable" (NA)**.

The survey is due by **February 28, 2025**. A <u>confirmation email</u> will be sent to the email address that you provide upon submission.

```{=html}
<iframe id="contentFrame" width="100%" height="1600px" frameborder="0" scrolling="no"
  src="psi-un-goals-survey-revised.html" style="overflow-y: hidden;">
</iframe>
```
