---
title: Externalities
subtitle: Classwork 1
date: last-modified
code-fold: true
execute: 
  echo: true
  warning: false
  message: false
from: markdown+emoji
---
```{r}
#| include: false

library(knitr)
library(rmarkdown)
library(tidyverse)
library(skimr)
library(ggthemes)
library(hrbrthemes)

theme_set(theme_ipsum() +
          theme(strip.background =element_rect(fill="lightgray"),
                axis.title.x = element_text(size = rel(1.5)),
                axis.title.y = element_text(size = rel(1.5)),
                legend.title = element_text(size=rel(1.25))
                ))
```

## Question 1. Static Efficiency

The demand curve for a product is given by $Q_{D} = 400-20P$ and the supply curve for a product is given by $Q_{S} = 16P-32$.

a. Illustrate the demand curve and the supply curve on the same graph.
b. Find the equilibrium price and quantity.  
c. Find numerical values for the consumer surplus and the producer surplus.
d. Identify consumer surplus and producer surplus on your graph.
e. Find numerical values for the total willingness to pay for the equilibrium quantity and the total variable cost of supplying the equilibrium quantity. Identify these areas on your graph.


<br><br>

## Question 2. Externalities

The marginal benefit curve for a product is given by $MB = 100-20Q$ and the marginal private cost curve for a product is given by $MC_{P} = 10 + 0.5Q$.

a. Find the equilibrium price and quantity and illustrate graphically.
b. Suppose the marginal external cost (the marginal increase in damages from pollution) for producing one unit of a product is given by $MC_{E} = 0.5Q$. Find the marginal social cost $MC_{S} = MC_{P} + MC_{E}$. Illustrate this new cost curve on your graph.
c. Find the socially optimal equilibrium price and quantity.

<br><br>
