---
title: "Topic 4 - High Seas Fisheries"
# subtitle: Research 1
date: last-modified
code-fold: true
execute: 
  echo: false
  warning: false
  message: false
from: markdown+emoji
---
```{r}
#| include: false
#| eval: true

library(knitr)
library(rmarkdown)
library(tidyverse)
library(skimr)
library(ggthemes)
library(hrbrthemes)
library(grid)

theme_set(theme_minimal() +
          theme(strip.background =element_rect(fill="lightgray"),
                axis.title.x = element_text(size = rel(1), hjust = 1 ),
                axis.title.y = element_text(size = rel(1), 
                                            angle = 0,
                                            margin = margin(0,10,0,0)))
          )

```


# Fisheries Economics and International Treaty Negotiations

Imagine you are a fisheries economist working at NOAA and are preparing to negotiate a new United Nations treaty for the international management of the High Seas. Below are key questions to consider when analyzing the potential impacts of this treaty. Refer to the provided article and podcast for the context and insights.

- [_Planet Money, NPR_, "The Less Deadly Catch"](https://www.npr.org/sections/money/2015/11/04/454698093/episode-661-the-less-deadly-catch)
- [_Alastair Bland_, "Could the High Seas be Closed to Fishing?"](https://deeply.thenewhumanitarian.org/oceans/articles/2018/08/15/could-the-high-seas-be-closed-to-fishing)

<br>

## 1. Common Pool Resources in the High Seas

### Challenges of Managing Common Pool Resources
- Explain how the fish of the High Seas represent a common pool resource.
- What properties of these resources make them particularly challenging to manage, as discussed in the article and podcast?

<br>

## 2. Endangered Species Fishing as a Collective Action Problem

### Collective Action Challenges
- Discuss why the fishing of an endangered species in the High Seas can be considered a collective action problem.
- How do the benefits and impacts of fishing this species, as outlined in the article and podcast, complicate management efforts?

<br>

## 3. Comparison of Alaskan and High Seas Fisheries

### Environmental and Economic Impacts
- Compare the environmental impacts of the Alaskan fishery to those of fisheries in the High Seas.
- Compare the economic impacts of both fisheries, referencing the issues highlighted in the article and podcast.

<br>

## 4. Impact of Alaskan Fishery Management Reforms

### Influence of Reforms on Stakeholders
- Describe how reforms in the management of Alaskan fisheries have influenced:
  - (a) The health of the fishery.
  - (b) Boat captains.
  - (c) Crew members on fishing vessels.
  - (d) Fish consumers.
- Compare these impacts with potential outcomes for the High Seas, as discussed in the article and podcast.
