---
title: Homework 1
subtitle: ""
date: last-modified
from: markdown+emoji
comments: false
code-fold: true

execute: 
  warning: false
  message: false
  fig-width: 9
  fig-height: 7
  fig-align: center
---
```{r}
#| include: false

library(tidyverse)
library(skimr)
library(DT)
library(hrbrthemes)

theme_set(theme_ipsum() +
          theme(strip.background =element_rect(fill="lightgray"),
                axis.title.x = element_text(size = rel(1.5)),
                axis.title.y = element_text(size = rel(1.5)),
                legend.title = element_text(size=rel(1.25))
                ))
```


# Question 1. Externalities and Economic Development
The demand function for oil is $q_d = 4 - p$, and the supply function is $q_s = p - 2$, where $p$ is the price of oil per barrel, and $q$ is the quantity of oil in millions of barrels per day. Using this information, solve the following problems:

a. Graph the supply and demand functions on the same coordinate plane.

b. Determine the market equilibrium price and quantity of oil.

c. Calculate the consumer surplus and producer surplus at the market equilibrium.

d. Oil consumption causes environmental damage. Suppose the marginal damage of oil pollution is given by $MD = q + 1$. Calculate:
   (1) The socially optimal level of oil use
   (2) The deadweight loss due to pollution at the market equilibrium

e. Due to economic development, the future demand for oil increases, resulting in a new demand function $q_d' = 8 - p$. Determine:
   (1) The new market equilibrium price and quantity
   (2) The new socially optimal level of oil use
   (2) The deadweight loss due to pollution at the market equilibrium in the future

f. Propose and briefly explain two distinct public policies that could be implemented to mitigate the environmental damages and reduce the burden on future generations. Discuss the potential effectiveness and challenges of each policy.

g. Suppose the government decides to impose a Pigouvian tax to internalize the external costs of oil pollution. Calculate the optimal tax rates in the present and in the future and explain how it would affect the market equilibrium and social welfare.


<br><br>

# Question 2. Provision of Public Goods
A community lives near a forest. The forest provides wood, which the villagers can use for various purposes like heating, building, or selling. However, the forest also acts as a carbon sink, absorbing carbon dioxide and providing fresh air, and is home to various wildlife. If too many trees are cut down, the forest will degrade, leading to loss of these environmental benefits.

There are $N$ number of identical villagers. Each villager is endowed with $\$y$, and must decide how much of their endowment to invest in a communal fund for forest conservation and how much to keep for themselves. Let $g_{i}$ denote each villager's contribution to the communal fund. 

The total amount of dollars in the communial fund is multiplied by some constant factor $R$, where $1 < R < N$. The multiplied amount is then equally distributed among all villagers, irrespective of their individual contributions.

Each villager $i$'s utility is as follows:
$$
\begin{align}
U_{i} &= y - g_{i} + \frac{R}{N} \times G\\
&= y - g_{i} + \frac{R}{N} \times \left(\, g_{i} + G_{-i} \,\right),
\end{align}
$$
where $G$ is the total amount of dollars collected for the communial fund, and $G_{-i} = G - g_{i}$.

a. Using calculus and graph, determine the equilibrium contribution ($g_{i}^{*}$) for each villager.
b. The forest manager, who is external to the community, aims to maximize the community's social welfare ($SW$). Note that the social welfare is the sum of the individual villager's utility. Calculate the socially optimal level of $g_i$ that maximizes $SW$. How does this differ from the equilibrium contribution?

$$
\begin{align}
SW &= U_{1} + U_{2} + \cdots + U_{N}\\
&= N \times U_{i}\qquad\text{ for any villager }\; i = 1, 2, \cdots, N\\
&= N \times \left(\,y - g_{i} + \frac{R}{N} \times G\,\right) \\
&= Ny +( R - 1 )\times G\\
&= Ny +( R - 1 )\times (G_{-i} + g_{i})\\
&= Ny +( R - 1 )\times (g_{1} + g_{2} + \cdots + g_{N})
\end{align}
$$

c. The forest manager decides to implement a matching grant program to encourage contributions to the forest conservation fund. For every dollar contributed by a villager, the program will contribute an additional $m$ dollars (where $0 < m < 1$). The utility function for each villager $i$ now becomes:
$$
\begin{align}
U_{i}^{'} &= y - g_{i} + \frac{R}{N} \times (1 + m) \times G\\
&= y - g_{i} + \frac{R}{N} \times (1 + m) \times \left(\, g_{i} + G_{-i} \,\right),
\end{align}
$$

Determine the minimum value of $m$ that would induce villagers to contribute the socially optimal level of $g_i$ found in part (b). Show your work.

d. Using the minimum value of $m$ found in part (c), calculate the total cost of implementing the matching grant program to the forest manager. Assume all villagers contribute the socially optimal amount.

e. Calculate the change in social welfare ($\Delta SW = SW^{'} - SW$) with the introduction of the matching grant program. Compare this change to the cost of the program calculated in part (d). Is the change in $SW$ greater than, equal to, or less than the cost of the program to the forest manager? Justify your answer analytically.

e. Discuss the practical implications and potential challenges of implementing such a matching grant program in the context of community forest management.

