---
title: Homework 5
subtitle: ""
date: last-modified
from: markdown+emoji
comments: false
# code-fold: true

echo: false
eval: true

execute: 
  warning: false
  message: false
  fig-width: 9
  fig-height: 7
  fig-align: center
---
```{r}
#| include: false

library(tidyverse)
library(skimr)
library(DT)
library(hrbrthemes)

theme_set(theme_ipsum() +
          theme(strip.background =element_rect(fill="lightgray"),
                axis.title.x = element_text(size = rel(1.5)),
                axis.title.y = element_text(size = rel(1.5)),
                legend.title = element_text(size=rel(1.25))
                ))
```

# Question 1. 
Farmer’s marginal net benefit of water use is given by:
$$
MNB_{f} = 10 - Q_{f}
$$

Urban household’s marginal net benefit of water use is:
$$
MNB_{u} = 20 - 2Q_{u}
$$

The total water supply is $Q_{total} = 15$ units for any level of price.

## Q1a
Find the efficient allocation of water use.

<br>

## Q1b
If water supply drops to 8 units for any level of price, what will be the efficient allocation of water use?


<br><br><br>


# Question 2. 
Water is an essential resource. For that reason moral considerations exert considerable pressure to assure that everyone has access to at least enough water to survive. Yet it appears that equity and efficiency considerations may conflict. Providing water at zero cost is unlikely to support efficient use (marginal cost is too low), while charging everyone the market price (especially as scarcity sets in) may result in some poor households not being able to afford the water they need. Discuss how block-rate pricing attempts to provide some resolution to this dilemma. How would it work?


<br><br><br>

# Question 3.
Assume that the relationship between the growth of a fish population and the population size can be expressed as $g = 4P – 0.1P^{2}$, where $g$ is the growth in tons and $P$ is the size of the population (in thousands of tons). Given a price of \$100 a ton, the marginal benefit of smaller population sizes (and hence larger catches) can be computed as $20P – 400$.

## Q3a
- Compute the population size that is compatible with the maximum sustainable yield. 
- What would be the size of the annual catch if the population were to be sustained at this level?

<br>

## Q3b
If the marginal cost of additional catches (expressed in terms of the population size) is $MC = 2(160 – P)$, what is the population size that is compatible with the efficient sustainable yield?




<br><br><br>

# Question 4. 
Consider a village of $N$ identical fishermen ( $i = 1, 2, 3, \cdots, N$ ) nearby the Erie Lake. They all have a choice of how much time they want to spend fishing per day, denoted by $a_{i}$. Thus, the total time of fishing per day in the village is given by:

$$
\sum_{i = 1}^{N} a_{i} = a_{1} + a_{2} + \cdots + a_{N}.
$$

Suppose the stock of fishes over time $S$ in the Erie Lake is represented by a function of the total time of fishing per day:

$$
\begin{align}
S &= 1000 - \sum_{i = 1}^{N} a_{i}\\ 
&= 1000 - ( a_{1} + a_{2} + \cdots + a_{N} )
\end{align}
$$

The amount of fishes fisherman $1$ catches is the fisherman $1$'s utility $U_{1}$, which is represented by:

$$
\begin{align}
U_{1} &= a_{1}\times S\\
&= a_{1}\times \left(\, 1000 - ( a_{1} + a_{2} + \cdots + a_{N} ) \,\right)
\end{align}
$$
Each fisherman $i$ chooses how much time to spend fishing per day ($a_{i}$) to maximize his utility ($U_{i}$).

<br>


## Q4a
- How much time will fisherman $1$ spend fishing per day if the government does not intervene?

<br>

## Q4b
- How much fishes will fisherman $1$ catch?

<br>

## Q4c
- If the fishermen jointly maximize the social welfare of the village, how much time each fisherman spend fishing per day and how much fishes each fisherman catch?

  - Social welfare is given by:
  
$$
\begin{align}
SW = U_{1} + U_{2} + \cdots + U_{N}
\end{align}
$$

<br>

## Q4d
- If there are 1,000 fishermen in the village, how much fish stock $S$ will be left in the Erie Lake after the scenarios outlined in Q4a/Q4b and in Q4c, respectively?
- Provide an intuitive explanation on how fish stocks in both scenarios are different.
- Make any policy suggestion on managing open access fishery in the village nearby the Erie Lake.




 