---
title: Homework 3
subtitle: ""
date: last-modified
from: markdown+emoji
comments: false
code-fold: true

execute: 
  warning: false
  message: false
  fig-width: 9
  fig-height: 7
  fig-align: center
---
```{r}
#| include: false

library(tidyverse)
library(skimr)
library(DT)
library(hrbrthemes)

theme_set(theme_ipsum() +
          theme(strip.background =element_rect(fill="lightgray"),
                axis.title.x = element_text(size = rel(1.5)),
                axis.title.y = element_text(size = rel(1.5)),
                legend.title = element_text(size=rel(1.25))
                ))
```



# Carbon Border Adjustment (CBA)

- For Homework Assignment 3, please refer to the following references:
  - [Carbon Border Adjustments: Design Elements, Options, and Policy Decisions](https://www.rff.org/publications/reports/carbon-border-adjustments-design-elements-options-and-policy-decisions/)
  - [Carbon Border Adjustments: Design Elements, Options, and Policy Decisions (PDF)](https://media.rff.org/documents/Report_23-14.pdf)
  - [Carbon Border Adjustment Mechanism: A new, green way of pricing carbon in imports to the EU](https://www.eeas.europa.eu/sites/default/files/documents/2023/Carbon%20Border%20Adjustment%20Mechanism.pdf)
  
<br>

## Question 1
- What is a Carbon Border Adjustment (CBA), and what is its main purpose?

<br>


## Question 2
- Which sectors are typically impacted by CBAs, and why?

<br>


## Question 3
- Describe the approach taken by the European Union’s Carbon Border Adjustment Mechanism (CBAM).

<br>


## Question 4
- What role do “baselines” play in CBAs, and how do they function in the U.S. Clean Competition Act (CCA)?

<br>


## Question 5
- How are fees typically structured in CBAs, and what are some variations across policies?

<br>


## Question 6
- What challenges exist in measuring the GHG intensity of products for CBAs?

<br>


## Question 7
- How do CBAs interact with domestic emissions reduction strategies?

<br>


## Question 8
- What exemptions or alliances are considered in CBAs, and how do they impact international trade?

<br>


## Question 9
- Why might CBAs raise concerns regarding compliance with World Trade Organization (WTO) rules?

<br>


## Question 10
- What questions remain unanswered about the effectiveness and fairness of CBAs?

<br>



<!-- # Suggested Model -->

<!-- - Agents -->
<!--   - Sweden Consumer -->
<!--   - Sweden Producer -->
<!--   - Sweden Government -->
<!--   - Indian Consumer -->
<!--   - Indian Producer -->
<!--   - Indian Government -->
<!--   - Social Planner (a global version) -->


<!-- - **Sweden Consumer** lives in Sweden and chooses how much to consume a Sweden good being sold in Sweden ( $q_{s}$ ) and an Indian good being sold in Sweden ( $\tilde{q}_{i}$ ). -->
<!-- - **Sweden Producer** locates in Sweden and chooses how much to produce a Sweden good being sold in Sweden ( $q_{s}$ ) and a Sweden good being sold in India ( $\tilde{q}_{s}$ ). -->

<!-- - **Indian Consumer** lives in India and chooses how much to consume an Indian good being sold in India ( $q_{i}$ ) and a Sweden good being sold in India ( $\tilde{q}_{s}$ ). -->
<!-- - **Indian Producer** locates in India and chooses how much to produce an Indian good being sold in India ( $q_{i}$ ) and an Indian good being sold in Sweden ( $\tilde{q}_{i}$ ). -->


<!-- - The climate damage in Sweden caused by carbon emissions from Sweden Producer and Indian Producer is denoted by  -->

<!-- $$ -->
<!-- D_{s} = D_{s}(q_{s} + \tilde{q}_{s} + q_{i} + \tilde{q}_{i}) -->
<!-- $$ -->

<!-- - The climate damage in India caused by carbon emissions from Sweden Producer and Indian Producer is denoted by  -->

<!-- $$ -->
<!-- D_{i} = D_{i}(q_{s} + \tilde{q}_{s} + q_{i} + \tilde{q}_{i}) -->
<!-- $$ -->


<!-- <br><br> -->

<!-- ## Sweden -->
<!-- ### Sweden Consumer -->

<!-- Given the Sweden's income ( $Y_{s}$ ), the price of a Sweden good in Sweden ( $p_{s}$ ), and the price of an Indian good in Sweden ( $\tilde{p}_{i}$ ), **Sweden Consumer** maximizes her utility: -->
<!-- $$ -->
<!-- \begin{align} -->
<!-- \max_{q_{s}, \tilde{q}_{i}}\;U_{s} = Y_{s} - p_{s}q_{s} - \tilde{p}_{i}\tilde{q}_{i} + V_{ss}(q_{s}) + V_{si}(\tilde{q}_{i}) -->
<!-- \end{align} -->
<!-- $$ -->

<!-- First-order conditions for Sweden Consumer's utility maximization problem are: -->
<!-- $$ -->
<!-- \begin{align} -->
<!-- q_{s}:&\qquad -p_{s} + V_{ss}' = 0 \tag{Demand-$q_{s}$}\\ -->
<!-- \tilde{q}_{i}:&\qquad -\tilde{p}_{i} + V_{si}'  = 0 \tag{Demand-$\tilde{q}_{i}$} -->
<!-- \end{align} -->
<!-- $$ -->

<!-- ### Sweden Producer -->

<!-- Given the price of a Sweden good in Sweden ( $p_{s}$ ) and the price of a Sweden good in India ( $\tilde{p}_{s}$ ), **Sweden Producer** maximizes her profit: -->
<!-- $$ -->
<!-- \begin{align} -->
<!-- \max_{q_{s}, \tilde{q}_{s}}\;\Pi_{s} = p_{s}q_{s} + \tilde{p}_{s}\tilde{q}_{s} - C_{ss}( q_{s} )  - C_{si}( \tilde{q}_{s} )  -->
<!-- \end{align} -->
<!-- $$ -->

<!-- First-order conditions for Sweden Producer's profit maximization problem are: -->
<!-- $$ -->
<!-- \begin{align} -->
<!-- q_{s}:&\qquad p_{s} - C_{ss}' = 0 \tag{Supply-$q_{s}$}\\ -->
<!-- \tilde{q}_{s}:&\qquad \tilde{p}_{s} + C_{si}'  = 0 \tag{Supply-$\tilde{q}_{s}$} -->
<!-- \end{align} -->
<!-- $$ -->

<!-- <br><br> -->

<!-- ## India -->
<!-- ### Indian Consumer -->

<!-- Given the India's income ( $Y_{i}$ ), the price of an Indian good in India ( $p_{i}$ ), and the price of a Sweden good in India ( $\tilde{p}_{s}$ ), **Indian Consumer** maximizes his utility: -->

<!-- $$ -->
<!-- \begin{align} -->
<!-- \max_{q_{i}, \tilde{q}_{s}}\;U_{i} = Y_{i} - p_{i}q_{i} - \tilde{p}_{s}\tilde{q}_{s} + V_{ii}(q_{i}) + V_{is}(\tilde{q}_{s}) -->
<!-- \end{align} -->
<!-- $$ -->


<!-- First-order conditions for Indian Consumer's utility maximization problem are: -->
<!-- $$ -->
<!-- \begin{align} -->
<!-- q_{i}:&\qquad -p_{i} + V_{ii}' = 0 \tag{Demand-$q_{i}$}\\ -->
<!-- \tilde{q}_{s}:&\qquad -\tilde{p}_{s} + V_{is}'  = 0 \tag{Demand-$\tilde{q}_{s}$} -->
<!-- \end{align} -->
<!-- $$ -->

<!-- ### Indian Producer -->

<!-- Given the price of an India good in India ( $p_{i}$ ) and the price of an Indian good in Sweden ( $\tilde{p}_{i}$ ), **Indian Producer** maximizes her profit: -->
<!-- $$ -->
<!-- \begin{align} -->
<!-- \max_{q_{i}, \tilde{q}_{i}}\;\Pi_{i} = p_{i}q_{i} + \tilde{p}_{i}\tilde{q}_{i} - C_{ii}( q_{i} )  - C_{is}( \tilde{q}_{i} )  -->
<!-- \end{align} -->
<!-- $$ -->

<!-- First-order conditions for Indian Producer's profit maximization problem are: -->
<!-- $$ -->
<!-- \begin{align} -->
<!-- q_{i}:&\qquad p_{i} - C_{ii}' = 0 \tag{Supply-$q_{i}$}\\ -->
<!-- \tilde{q}_{i}:&\qquad \tilde{p}_{i} + C_{is}'  = 0 \tag{Supply-$\tilde{q}_{i}$} -->
<!-- \end{align} -->
<!-- $$ -->

<!-- <br><br> -->

<!-- ## Social Planner, a global version -->

<!-- The Social Planner allocates Sweden/Indian goods in Sweden/India maximizes the social welfare, taking into account the climate damages in Sweden and India -->

<!-- $$ -->
<!-- \begin{align} -->
<!-- \max_{q_{s}, \tilde{q}_{s}, q_{i}, \tilde{q}_{i}}\; SW &= U_{s} + U_{i} + \Pi_{s} + \Pi_{i} - (D_{s} + D_{i})\\ -->
<!-- &=\; Y_{s} + Y_{i}\\&\quad + V_{ss}(q_{s}) + V_{si}(\tilde{q}_{i}) + V_{ii}(q_{i}) + V_{is}(\tilde{q}_{s})\\&\quad - C_{ss}( q_{s} ) - C_{si}( \tilde{q}_{s} )   - C_{ii}( q_{i} ) - C_{is}( \tilde{q}_{i} )\\&\quad - D_{s}(q_{s} + \tilde{q}_{s} + q_{i} + \tilde{q}_{i}) - D_{i}(q_{s} + \tilde{q}_{s} + q_{i} + \tilde{q}_{i}) -->
<!-- \end{align} -->
<!-- $$ -->

<!-- First-order conditions for the Social Planner's socal welfare maximization problem are: -->
<!-- $$ -->
<!-- \begin{align} -->
<!-- q_{s}:&\qquad V_{ss}' - C_{ss}' - D_{s}' - D_{i}' = 0 \tag{Opt-$q_{s}$}\\ -->
<!-- \tilde{q}_{s}:&\qquad V_{is}' - C_{si}' - D_{s}' - D_{i}' = 0 \tag{Opt-$\tilde{q}_{s}$}\\ -->
<!-- q_{i}:&\qquad V_{ii}' - C_{ii}' - D_{s}' - D_{i}' = 0 \tag{Opt-$q_{i}$}\\ -->
<!-- \tilde{q}_{i}:&\qquad V_{si}' - C_{is}' - D_{s}' - D_{i}'  = 0 \tag{Opt-$\tilde{q}_{i}$} -->
<!-- \end{align} -->
<!-- $$ -->

<!-- # Tasks -->


<!-- ## Task 1 - Globally optimal resource allocations -->
<!-- - Derive the first order conditions for the Social Planner's maximization problem, which characterizes the globally optimal resource allocations $\left(\,\left\{q_{s}^{o}, \tilde{q}_{s}^{o}, q_{i}^{o}, \tilde{q}_{i}^{o}\right\}\,\right)$ and determine the globally optimal carbon tax.  -->

<!-- <br> -->
<!-- <br> -->

<!-- ## Task 2 - Markets under the Local Carbon Tax System -->

<!-- - Let $t_{ss}$ denote **Swedish Government**'s carbon tax imposed on goods produced by Sweden Producer ( $q_{s}$ and  $\tilde{q}_{s}$ ). -->

<!-- - Let $t_{ii}$ denote **Indian Government**'s carbon tax imposed on goods produced by Indian Producer ( $q_{i}$ and  $\tilde{q}_{i}$ ). -->


<!-- - Under the local carbon tax, consider the markets for the following four goods: -->
<!--   - A Sweden good being sold in Sweden ( $q_{s}$ ) -->
<!--   - An Indian good being sold in Sweden ( $\tilde{q}_{i}$ ) -->
<!--   - An Indian good being sold in India ( $q_{i}$ ) -->
<!--   - A Sweden good being sold in India ( $\tilde{q}_{s}$ ) -->

<!-- - Derive the demand and supply curves for each market using the first-order conditions for the Consumers' and the Producers' problems under the local carbon tax. -->

<!-- - Draw the linear demand and supply functions, assuming the quadratic form of utility and cost functions. -->

<!-- - Describe how the carbon taxes shift the supply functions. -->

<!-- <br> -->
<!-- <br> -->



<!-- ## Task 3 - Optimal Carbon Tax -->
<!-- - To achieve the globally optimal resource allocations $\left(\,\left\{q_{s}^{o}, \tilde{q}_{s}^{o}, q_{i}^{o}, \tilde{q}_{i}^{o}\right\}\,\right)$, what rate of carbon taxes should each government set? -->

<!-- <br> -->
<!-- <br> -->




<!-- ## Task 4 - Hypothetical Scenario -->

<!-- - Suppose the Sweden government imposes the optimal carbon tax that internalizes the global climate damage ( $D = D_{s} + D_{i}$ ), while the Indian government imposes the locally optimal carbon tax that internalizes only the local climate damage ( $D_{i}$ ). -->

<!-- - Design the CBAM that the Sweden government induces the Indian Producer to produce the globally optimal level of the good being sold in Sweden. -->
<!--   - That is, for the Sweden government to impose tariff $(\,t_{si}\,)$ on Indian goods being sold in Sweden. -->


<!-- <br> -->
<!-- <br> -->






