---
title: "ECON 341: Team Project"
author: 
  - Mackenzie Reigle
  - <i>Feedback provided by</i> Byeong-Hak Choe
date: last-modified
execute: 
  echo: false
  eval: true
  warning: false
  message: false
toc: true
---

# Feedback

-	Expand on the Alaskan Fishery Case Study: Provide more background on how Alaskan fisheries are managed and what lessons can be drawn.
-	Emphasize Global Cooperation: Stress the importance of international collaboration in addressing the issue, given that the high seas are beyond any single nation’s jurisdiction.
-	Discuss Potential Economic Impacts: Explore how overfishing and policy changes affect the economies of fishing nations, especially those heavily reliant on fishing industries.

- Consider summarizing the following additional reference:
  - Sala et. al., *The Economics of Fishing the High Seas*, Science Advances (2018) [*[Link]*](https://bcecon.github.io/econ-rw/4-app-SalaEtAl-science-2018-high-seas.pdf)


## Theoretical Framework Details
- Elaborate on the theoretical underpinnings of the economic model. 
  - To understand the challenges in managing high seas fisheries, it is useful to apply economic theories related to common-pool resources, externalities, and collective action problems.
  - Lectures on Fishery Management should be useful.

### The Harvesting Decision: Fisheries
Defining the efficient sustainable yield for a fishery begins with a characterization of the biological relationship between the growth for the biomass and the size of the biomass. The standard representation of this relationship is

$$
\begin{align}
g = rS\left(1-\frac{S}{k}\right)\tag{1}
\end{align}
$$

- $g$: the growth rate of the biomass,
- $r$: the intrinsic growth rate for this species,
- $S$: the size of the biomass, and
- $k$: the carrying capacity of the habitat.

Since we want to choose the most efficient sustained yield, we must limit the possible outcomes we shall consider to those that are sustainable. Here we define a sustainable harvest level, $h_{s}$, as one that equals the growth of the population. Hence:
$$
\begin{align}
h_{s} = rS\left(1-\frac{S}{k}\right) \tag{2}
\end{align}
$$

The next step is to define the size of the harvest as a function of the amount of effort expended. This is traditionally modeled as
$$
\begin{align}
h = qES\tag{3}
\end{align}
$$

- $q$: a constant (known as the “catchability coefficient”), and
- $E$: the level of effort.


The next step is to solve for sustained yields as a function of effort. This can be derived using a two-step procedure. First, we express $S$ in terms of $E$. Then we use this newly derived expression for $S$ along with the relationship in Equation (3) to derive the sustained yield expressed in terms of effort.

To define $S$ in terms of $E$, we can substitute Equation (3) into Equation (2):
$$
\begin{align}
qES = rS\left(1-\frac{S}{k}\right) \tag{4}
\end{align}
$$
Rearranging terms yields
$$
\begin{align}
S = k\left(1-\frac{qE}{r}\right) \tag{5}
\end{align}
$$
Using $S = \frac{h}{qE}$ from Equation (3) and rearranging terms to solve for $h$ yields
$$
\begin{align}
h_{s} = qEk - \frac{q^{2}kE^{2}}{r} \tag{6}
\end{align}
$$

It is now possible to find the maximum sustainable effort level by taking the derivative of the right-hand side of Equation (6) with respect to effort ($E$) and setting the result equal to zero.

The maximum condition is
$$
\begin{align}
qk - 2\frac{q^{2}kE}{r} = 0 \tag{7}
\end{align}
$$

So
$$
\begin{align}
E_{msy} = \frac{r}{2q} \tag{8}
\end{align}
$$

- $E_{msy}$: the level of effort that is consistent with the maximum sustained yield.

Can you see how to solve for the maximum sustainable yield, $h_{msy}$? (Hint: remember how the maximum sustained yield was defined in terms of effort in Equation (6)?)

To conduct the economic analysis, we need to convert this biological information to a net benefits formulation. The benefit function can be defined by multiplying Equation (6) by $P$, the price received for a unit of harvest. Assuming a constant marginal cost of effort, $a$, allows us to define total cost as equal to $aE$. Subtracting the total cost of effort from the revenue function produces the net benefits function:
$$
\begin{align}
\text{Net benefits} = PqEk - \frac{Pq^{2}kE^{2}}{r} - aE. \tag{9}
\end{align}
$$

Since the efficient sustained effort level is the level that maximizes Equation (9), we can derive it by taking the derivative of Equation (9) with respect to effort ($E$) and setting the derivative equal to zero:

$$
\begin{align}
Pqk - \frac{2Pkq^{2}E}{r} - a = 0 \tag{10}
\end{align}
$$

Rearranging terms yields
$$
\begin{align}
E = \frac{r}{2q}\left(1-\frac{a}{Pqk}\right) \tag{11}
\end{align}
$$

Note that this effort level is smaller than that needed to produce the maximum sustainable yield. Can you see how to find the efficient sustainable harvest level? Finally, we can derive the free-access equilibrium by setting the net benefits function in Equation (9) equal to zero and solving for the effort level.
Rearranging terms yields
$$
\begin{align}
E = \frac{r}{q}\left(1-\frac{a}{Pqk}\right) \tag{12}
\end{align}
$$

Note that this is larger than the efficient sustained level of effort. It may or may not be larger than the level of effort needed to produce the maximum sustained yield. That comparison depends on the specific values of the parameters.
